spring.security.oauth2.client.registration.github.client-id=Ov23liEFr6HegUWtUvD0
spring.security.oauth2.client.registration.github.client-secret=4211248225a0c5b265785792e23690560ab3f713


server.port=8082
spring.security.oauth2.client.registration.google.client-id=************************
spring.security.oauth2.client.registration.google.client-secret=************************